### ISSUE TITLE
网站太酷

### ISSUE THREAD

**Issue by yihui** [Selaginella99/Selaginella99.github.io#1]
这么 :cool: 你家里人造吗？ :astonished:

 :camera:  :zap:  :camera:  :zap:  :camera: :zap:

**Comment by Selaginella99** [comment]
@yihui: 家属来解释一下？grimacing @teacheRforV

**Comment by Selaginella99** [comment]
@yihui 家属来解释一下？:grimacing: @teacheRforV

**Comment by teacheRforV** [comment]
@yihui @Selaginella99 
What else can I say ... :laughing: Just keep calm and enjoy coolness! :sunglasses: 
<img src="http://i.imgur.com/v1xBrAr.png"></img>

**Comment by yihui** [comment]
对回答感到很满意。标记为已解决。顺带再次照相留念 :camera:
